package ex.rr.adminpanel.database;

import ex.rr.adminpanel.annotations.Cron;
import ex.rr.adminpanel.enums.ActionType;
import ex.rr.adminpanel.enums.InputType;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

/**
 * The {@code Trigger} class represents the trigger database entity.
 * <ul>
 *     <li>{@code id} - Autogenerated id.</li>
 *     <li>{@code input} - Instructions used to fetch results.</li>
 *     <li>{@code inputType} - How the data will be retrieved.
 *         <pre>Values: QUERY, CURL, TEXT</pre></li>
 *     <li>{@code actionType} - Action to be executed when task returns data.
 *         <pre>Values: LOG, TEAMS_MESSAGE, REST</pre></li>
 *     <li>{@code cron} - Cron expression used for task execution</li>
 *     <li>{@code enabled} - TaskDefinition won't be scheduled if set to false</li>
 * </ul>
 * <p><i>Note: getters/setters intentionally created without Lombok.@Data to work with Vaadins Binder</i></p>
 *
 * @author  rromanowicz
 * @see     InputType
 * @see     ActionType
 * @see     ex.rr.adminpanel.scheduler.TaskDefinition
 */
@Entity
@Table(name = "TRIGGER")
public class Trigger {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    String id;
    @NotEmpty
    String input;
    @NotNull
    InputType inputType;
    @NotNull
    ActionType actionType;
    @NotEmpty
    @Cron
    String cron;
    @NotNull
    Boolean enabled;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    public InputType getInputType() {
        return inputType;
    }

    public void setInputType(InputType inputType) {
        this.inputType = inputType;
    }

    public ActionType getActionType() {
        return actionType;
    }

    public void setActionType(ActionType actionType) {
        this.actionType = actionType;
    }

    public String getCron() {
        return cron;
    }

    public void setCron(String cron) {
        this.cron = cron;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}
