logging:
  level:
    root: WARN
    ex:
      rr: INFO

server:
  port: 8080
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    user: guest
  #    password: guest
  #    listener:
  #      simple:
  #        default-requeue-rejected: false


  datasource:
    jdbcUrl: jdbc:h2:mem:testDb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver

    local:
      jdbcUrl: jdbc:h2:mem:localDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:local_data.sql';
      username: sa
      password: password
      driverClassName: org.h2.Driver
    dev:
      jdbcUrl: jdbc:h2:mem:devDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:dev_data.sql';
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver
    sit:
      jdbcUrl: jdbc:h2:mem:sitDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:sit_data.sql';
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver
    sat:
      jdbcUrl: jdbc:h2:mem:satDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:sat_data.sql';
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver
    prod:
      jdbcUrl: jdbc:h2:mem:prodDb;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\;RUNSCRIPT FROM 'classpath:prod_data.sql';
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,com.example.vaadin

app:
  secret:
    salt: ${SALT}