INSERT INTO DB_TRIGGER(ID, ENABLED, QUERY, TYPE, CRON) VALUES (1, 0, 'SELECT * FROM DUAL;', 0,  '0,30 * * * * *');
INSERT INTO DB_TRIGGER(ID, ENABLED, QUERY, TYPE, CRON) VALUES (2, 0, 'Hello Cron!', 1,  '*/10 * * * * *');
COMMIT;