CREATE TABLE IF NOT EXISTS DB_TRIGGER(
    ID INT PRIMARY KEY,
    QUERY TEXT,
    TYPE NUMBER,
    CRON VARCHAR(50),
    ENABLED NUMBER
);

CREATE SEQUENCE "DB_TRIGGER_SEQ" MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 50 START WITH 99 NOCACHE NOCYCLE;
