CREATE TABLE IF NOT EXISTS TRIGGER(
    ID VARCHAR(50) PRIMARY KEY,
    INPUT TEXT,
    INPUT_TYPE NUMBER,
    ACTION_TYPE NUMBER,
    CRON VARCHAR(50),
    ENABLED NUMBER
);

--CREATE SEQUENCE "TRIGGER_SEQ" MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 50 START WITH 99 NOCACHE NOCYCLE;

CREATE TABLE IF NOT EXISTS TEMPLATE(
    ID NUMBER PRIMARY KEY,
    TEMPLATE TEXT
);

CREATE SEQUENCE "TEMPLATE_SEQ" MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 50 START WITH 99 NOCACHE NOCYCLE;
