package ex.rr.adminpanel.data.database;

import ex.rr.adminpanel.data.models.templates.page.PageTemplate;
import jakarta.persistence.*;
import lombok.Data;



/**
 * The {@code Template} class represents the template database entity
 * <ul>
 *     <li>{@code id} - Autogenerated id.</li>
 *     <li>{@code template} - JSON string with PageTemplate definition.</li>
 *     <li>{@code @Transient pageTemplate} - Parsed object required for further processing.</li>
 * </ul>
 *
 * @author rromanowicz
 * @see PageTemplate
 */
@Data
@Entity
@Table(name = "T_TEMPLATE")
public class Template {

    @Id
    @GeneratedValue
    private Integer id;

    @Lob
    @Column(columnDefinition = "CLOB NOT NULL")
    private String templateJson;

    private boolean active;

}
